openapi: 3.0.0
info:
  title: Custom Coloring Book API - Feedback
  version: 1.1.0

paths:
  /feedback:
    post:
      summary: Submit feedback for the application
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  description: The ID of the user submitting the feedback (optional)
                  example: 12345
                feedback:
                  type: string
                  maxLength: 1000
                  description: The feedback message
                  example: "I love this app!"
              required:
                - feedback
            example:
              user_id: 12345
              feedback: "I love this app!"
      responses:
        '201':
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message
                example:
                  message: Feedback submitted successfully
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: An error message
                example:
                  message: Invalid input, please provide a valid feedback message
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: An error message
                example:
                  message: Internal server error, please try again later
